name: Rust

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run tests
        run: |
          cargo test --verbose
          wasm-pack test --headless --chrome
          wasm-pack test --headless --firefox

      - name: Build
        run: |
          cargo build --verbose
          wasm-pack build --dev -- --verbose
